/**
 * OCAP design tokens extracted from screen.png (Feed), screen2.png (Map), screen3.png (Post).
 * Per-screen lime and neutrals vary slightly; use the screen namespace for pixel fidelity.
 */

export const tokens = {
  feed: {
    lime: "#E2FF00",
    black: "#000000",
    white: "#FFFFFF",
    page: "#FFFFFF",
    locationPill: "#EDEDED",
    chipInactiveBg: "#E0E0E0",
    chipInactiveText: "#666666",
    card: "#F9F9F9",
    cardBorder: "rgba(0,0,0,0.06)",
    metaText: "#666666",
    urgentCard: "#1A1A1A",
    verified: "#1D9BF0",
    navInactive: "#707070",
    chipRadiusPx: 2,
    cardRadiusPx: 4,
  },
  map: {
    lime: "#E2FF00",
    black: "#000000",
    white: "#FFFFFF",
    page: "#F5F5F5",
    toggleInactiveBg: "#E5E5E5",
    searchBorder: "#000000",
    searchShadow: "#141400",
    gridLine: "#BDBDBD",
    secondaryText: "#757575",
    shareButtonBg: "#E0E0E0",
    cardDivider: "#E0E0E0",
    hardShadow: "4px 4px 0 0 #000000",
    radiusPx: 0,
  },
  post: {
    lime: "#E0FF00",
    black: "#000000",
    white: "#FFFFFF",
    page: "#FAFAFA",
    inputBg: "#F2F2F2",
    label: "#8C8C8C",
    wageCard: "#1A1A1A",
    progressTrack: "#E8E8E8",
    saveButtonBg: "#E8E8E8",
    radiusPx: 2,
    buttonShadowOffsetPx: 3,
  },
  type: {
    fontSans: ['Inter', 'system-ui', 'sans-serif'] as const,
    /** Page title / hero */
    titleLg: ["32px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" }] as const,
    titleMd: ["18px", { lineHeight: "1.2", fontWeight: "800" }] as const,
    button: ["14px", { lineHeight: "1", fontWeight: "800" }] as const,
    label: ["11px", { lineHeight: "1.2", fontWeight: "500", letterSpacing: "0.08em" }] as const,
    meta: ["11px", { lineHeight: "1.2", fontWeight: "700" }] as const,
    employerSub: ["10px", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "0.06em" }] as const,
    navLabel: ["10px", { lineHeight: "1", fontWeight: "800" }] as const,
    priceLg: ["28px", { lineHeight: "1", fontWeight: "900" }] as const,
    mapTitle: ["20px", { lineHeight: "1.15", fontWeight: "900" }] as const,
    postInput: ["17px", { lineHeight: "1.2", fontWeight: "700" }] as const,
    wageValue: ["40px", { lineHeight: "1", fontWeight: "900" }] as const,
  },
  space: {
    screenX: 20,
    screenY: 16,
    cardPad: 16,
    gapY: 16,
    sectionGap: 24,
    chipGap: 8,
  },
} as const

/** Tailwind `theme.extend` fragment — keep in sync with `theme` for React Native. */
export const tailwindThemeExtend = {
  colors: {
    ocap: {
      lime: {
        feed: tokens.feed.lime,
        map: tokens.map.lime,
        post: tokens.post.lime,
      },
      black: tokens.feed.black,
      white: tokens.feed.white,
      feed: {
        page: tokens.feed.page,
        location: tokens.feed.locationPill,
        chipInactive: tokens.feed.chipInactiveBg,
        chipText: tokens.feed.chipInactiveText,
        card: tokens.feed.card,
        meta: tokens.feed.metaText,
        urgent: tokens.feed.urgentCard,
        verified: tokens.feed.verified,
        navInactive: tokens.feed.navInactive,
      },
      map: {
        page: tokens.map.page,
        toggleInactive: tokens.map.toggleInactiveBg,
        searchShadow: tokens.map.searchShadow,
        grid: tokens.map.gridLine,
        muted: tokens.map.secondaryText,
        share: tokens.map.shareButtonBg,
        divider: tokens.map.cardDivider,
      },
      post: {
        page: tokens.post.page,
        input: tokens.post.inputBg,
        label: tokens.post.label,
        wage: tokens.post.wageCard,
        track: tokens.post.progressTrack,
        save: tokens.post.saveButtonBg,
      },
    },
  },
  fontFamily: {
    sans: [...tokens.type.fontSans],
  },
  fontSize: {
    "ocap-title": [...tokens.type.titleLg],
    "ocap-card-title": [...tokens.type.titleMd],
    "ocap-btn": [...tokens.type.button],
    "ocap-label": [...tokens.type.label],
    "ocap-meta": [...tokens.type.meta],
    "ocap-sub": [...tokens.type.employerSub],
    "ocap-nav": [...tokens.type.navLabel],
    "ocap-price-lg": [...tokens.type.priceLg],
    "ocap-map-title": [...tokens.type.mapTitle],
    "ocap-post-input": [...tokens.type.postInput],
    "ocap-wage": [...tokens.type.wageValue],
  },
  spacing: {
    "ocap-x": `${tokens.space.screenX}px`,
    "ocap-y": `${tokens.space.screenY}px`,
    "ocap-card": `${tokens.space.cardPad}px`,
    "ocap-section": `${tokens.space.sectionGap}px`,
  },
  borderRadius: {
    "ocap-feed-chip": `${tokens.feed.chipRadiusPx}px`,
    "ocap-feed-card": `${tokens.feed.cardRadiusPx}px`,
    "ocap-post": `${tokens.post.radiusPx}px`,
  },
  boxShadow: {
    "ocap-map-hard": tokens.map.hardShadow,
    "ocap-search": `4px 4px 0 0 ${tokens.map.searchShadow}`,
    "ocap-post-btn": `${tokens.post.buttonShadowOffsetPx}px ${tokens.post.buttonShadowOffsetPx}px 0 0 ${tokens.feed.black}`,
  },
} as const
